/*
 * This source file was generated by the Gradle 'init' task
 */
package com.edwardp20.libihatelogs;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainLog {
    @Test public boolean test() {
        MainLog classUnderTest = new MainLog();
        assertTrue("someLibraryMethod should return 'true'",classUnderTest.test());
    }
}
