/*
 * This source file was generated by the Gradle 'init' task
 */
package com.edwardp20.libihatelogs;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainLogTest {
    @Test public void test() {
        MainLog classUnderTest = new MainLog();
        assertTrue("test() should return true",classUnderTest.test());
    }
}
