/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.gradleup.shadow") version "9.6.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
}

testing {
    suites {
        // Configure the built-in test suite
        val test = named<JvmTestSuite>("test") {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

tasks.register("assembly") {
    dependsOn(tasks.shadowJar)
}


tasks.shadowJar {
    mergeServiceFiles()
    archiveBaseName.set("libihatelogs")  // jar 文件的基本名字
    archiveVersion.set("0.0-snapshot1")  // jar 文件的版本号
	archiveClassifier.set("")  // jar
    from("../LICENSE") {
        into("META-INF/legal/")
    }
    from("../NOTICE") {
        into("META-INF/legal/")
    }

}
